version: '3.2'

networks:
    backend-network:
        driver: bridge
    frontend-network:
        driver: bridge

volumes:
    db-data:
    home-dir:

services:
    &app-service app: &app-service-template
        image: registry.gitlab.com/tarampampam/laravel-in-docker/app:latest
        #build:
        #  context: ./docker/app
        #  dockerfile: Dockerfile
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ./:/app:rw
            - home-dir:/home/user
        hostname: *app-service
        environment:
            DB_HOST: db
            DB_PORT: &db-port 3306
            DB_DATABASE: &db-name app
            DB_USERNAME: &db-username user
            DB_PASSWORD: &db-pass secret
            SCHEDULE_PERIOD: 60
            FPM_PORT: &php-fpm-port 9000
            FPM_USER: "${USER_ID:-1000}"
            FPM_GROUP: "${GROUP_ID:-1000}"
            APP_ENV: local
            APP_DEBUG: 'true'
            HOME: /home/user
            PASH: /
        command: keep-alive.sh
        depends_on:
            - db
        networks:
            - backend-network
        build:
            context: './.docker/app'

    &php-fpm-service php-fpm:
        <<: *app-service-template
        user: 'root:root'
        restart: always
        hostname: *php-fpm-service
        ports: [ *php-fpm-port ]
        entrypoint: /fpm-entrypoint.sh
        command: php-fpm --nodaemonize -d "opcache.enable=0" -d "display_startup_errors=On" -d "display_errors=On" -d "error_reporting=E_ALL"
        networks:
            - backend-network
            - frontend-network


    nginx:
        image: registry.gitlab.com/tarampampam/laravel-in-docker/nginx:latest
        #build:
        #  context: ./docker/nginx
        #  dockerfile: Dockerfile
        restart: always
        working_dir: /usr/share/nginx/html
        environment:
            FPM_HOST: *php-fpm-service
            FPM_PORT: *php-fpm-port
            ROOT_DIR: '/app/public' # App path must equals with php-fpm container path
        volumes:
            - ./:/app:ro
        ports: [ '9999:80' ]
        depends_on:
            - *php-fpm-service
        networks:
            - frontend-network

    db:
        image: mysql:5.7.35
        restart: always
        environment:
            MYSQL_DATABASE: *db-name
            POSTGRES_USER: *db-username
            POSTGRES_PASSWORD: *db-pass
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports: [ *db-port, '3306:3306' ] # Port 15432 for connecting from localhost using, for example, data-grip
        networks:
            - backend-network
